steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/valeo-cp0992-dev/cloud-run-source-deploy/test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/valeo-cp0992-dev/cloud-run-source-deploy/test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'static-file-demo', '--image', 'europe-west1-docker.pkg.dev/valeo-cp0992-dev/cloud-run-source-deploy/test', '--region', 'europe-west1', '--platform', 'managed']
images:
- europe-west1-docker.pkg.dev/valeo-cp0992-dev/cloud-run-source-deploy/test
